#!/usr/bin/env php
<?php

require __DIR__ . '/vendor/autoload.php';

use Core\Support\Str;

$from = ROOT . '/.env.php.example';
$dest = ROOT . '/.env.php';

if (!file_exists($dest)) {
	copy($from, $dest);
}

// $env = file_get_contents($dest);
// $env = file($dest);dd($env);
// $env = require($dest);
// echo(var_export($env));

// $appKey = Str::random(32);
// file_put_contents($dest, preg_replace("~(app_key.*)=>\s*([\'\"]).*([\'\"])~m", "$1=> $2{$appKey}$3", $env));
