#!/usr/bin/env php
<?php

require __DIR__ . '/vendor/autoload.php';

use Homeleon\Support\Str;

$from = __DIR__ . '/.env.php.example';
$dest = __DIR__ . '/.env.php';

if (!file_exists($dest)) {
    if (!copy($from, $dest)) {
        throw new Exception('Config file could not be create');
    }

    echo "Config file has been succesfully created.\n";
}

echo "Generating token...\nCopy next token to .env.php config file in field 'app_key'\n";
echo Str::random(32);
echo "\n";
