#!/usr/bin/env php
<?php

require __DIR__ . '/vendor/autoload.php';

use Homeleon\Support\Str;

$from = __DIR__ . '/.env.php.example';
$dest = __DIR__ . '/.env.php';

if (!file_exists($dest)) {
    if (!copy($from, $dest)) {
        throw new Exception('Config file could not be create');
    }

    echo "Config file has been succesfully created.\n";
}

echo "Generating token...\n";
$appKey = Str::random(32);
$env = file_get_contents($dest);
file_put_contents($dest, preg_replace("~(app_key.*)=>\s*'.*'~m", "$1=> '{$appKey}'", $env));
echo "Success\n";
